//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.FileUploadFailure {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUploadFailure {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadFailure() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.FileUploadFailure.FileUploadFailure" +
                            "", typeof(FileUploadFailure).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string file_not_uploaded {
            get {
                return ResourceManager.GetString("file_not_uploaded", resourceCulture);
            }
        }
        
        internal static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        internal static string your_data_file_has_not_been_uploaded {
            get {
                return ResourceManager.GetString("your_data_file_has_not_been_uploaded", resourceCulture);
            }
        }
        
        internal static string download_error_report {
            get {
                return ResourceManager.GetString("download_error_report", resourceCulture);
            }
        }
        
        internal static string when_youve_fixed_the_errors_in_your_file {
            get {
                return ResourceManager.GetString("when_youve_fixed_the_errors_in_your_file", resourceCulture);
            }
        }
        
        internal static string pageTitle {
            get {
                return ResourceManager.GetString("pageTitle", resourceCulture);
            }
        }
        
        internal static string your_error_report_only_show_first_x_errors {
            get {
                return ResourceManager.GetString("your_error_report_only_show_first_x_errors", resourceCulture);
            }
        }
        
        internal static string you_should_correct_these_errors {
            get {
                return ResourceManager.GetString("you_should_correct_these_errors", resourceCulture);
            }
        }
        
        internal static string how_the_error_report_works {
            get {
                return ResourceManager.GetString("how_the_error_report_works", resourceCulture);
            }
        }
        
        internal static string next_steps {
            get {
                return ResourceManager.GetString("next_steps", resourceCulture);
            }
        }
        
        internal static string read_the_report_help_you_understand {
            get {
                return ResourceManager.GetString("read_the_report_help_you_understand", resourceCulture);
            }
        }
    }
}
