//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.ChangeComplianceSchemeOptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ChangeComplianceSchemeOptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ChangeComplianceSchemeOptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.FrontendSchemeRegistration.ChangeCo" +
                            "mplianceSchemeOptions", typeof(ChangeComplianceSchemeOptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string what_would_you_like_to_do {
            get {
                return ResourceManager.GetString("what_would_you_like_to_do", resourceCulture);
            }
        }
        
        internal static string choose_new_compliance_scheme {
            get {
                return ResourceManager.GetString("choose_new_compliance_scheme", resourceCulture);
            }
        }
        
        internal static string stop_using_compliance_scheme {
            get {
                return ResourceManager.GetString("stop_using_compliance_scheme", resourceCulture);
            }
        }
        
        internal static string error_message {
            get {
                return ResourceManager.GetString("error_message", resourceCulture);
            }
        }
    }
}
