//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.LandingPage {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LandingPage {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LandingPage() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.FrontendSchemeRegistration.LandingP" +
                            "age", typeof(LandingPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        internal static string you_have_created_an_account_for_x {
            get {
                return ResourceManager.GetString("you_have_created_an_account_for_x", resourceCulture);
            }
        }
        
        internal static string report_packaging_data {
            get {
                return ResourceManager.GetString("report_packaging_data", resourceCulture);
            }
        }
        
        internal static string organisation_name {
            get {
                return ResourceManager.GetString("organisation_name", resourceCulture);
            }
        }
        
        internal static string organisation_number {
            get {
                return ResourceManager.GetString("organisation_number", resourceCulture);
            }
        }
        
        internal static string tell_us_how_you_will_register_and_submit_data {
            get {
                return ResourceManager.GetString("tell_us_how_you_will_register_and_submit_data", resourceCulture);
            }
        }
        
        internal static string before_you_can_register_and_submit_data {
            get {
                return ResourceManager.GetString("before_you_can_register_and_submit_data", resourceCulture);
            }
        }
        
        internal static string _continue {
            get {
                return ResourceManager.GetString("continue", resourceCulture);
            }
        }
    }
}
