//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.ReviewCompanyDetails {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReviewCompanyDetails {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReviewCompanyDetails() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.ReviewCompanyDetails.ReviewCompanyD" +
                            "etails", typeof(ReviewCompanyDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string files_youve_uploaded {
            get {
                return ResourceManager.GetString("files_youve_uploaded", resourceCulture);
            }
        }
        
        internal static string file_name {
            get {
                return ResourceManager.GetString("file_name", resourceCulture);
            }
        }
        
        internal static string date_uploaded {
            get {
                return ResourceManager.GetString("date_uploaded", resourceCulture);
            }
        }
        
        internal static string uploaded_by {
            get {
                return ResourceManager.GetString("uploaded_by", resourceCulture);
            }
        }
        
        internal static string review_compliance_scheme {
            get {
                return ResourceManager.GetString("review_compliance_scheme", resourceCulture);
            }
        }
        
        internal static string how_to_submit_your_files {
            get {
                return ResourceManager.GetString("how_to_submit_your_files", resourceCulture);
            }
        }
        
        internal static string get_an_authorised_person_to_submit_the_files {
            get {
                return ResourceManager.GetString("get_an_authorised_person_to_submit_the_files", resourceCulture);
            }
        }
        
        internal static string report_packaging_data {
            get {
                return ResourceManager.GetString("report-packaging-data", resourceCulture);
            }
        }
        
        internal static string you_dont_have_permission_to_submit {
            get {
                return ResourceManager.GetString("you_dont_have_permission_to_submit", resourceCulture);
            }
        }
        
        internal static string files_uploaded {
            get {
                return ResourceManager.GetString("files_uploaded", resourceCulture);
            }
        }
        
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        internal static string go_to_your_account_homepage {
            get {
                return ResourceManager.GetString("go_to_your_account_homepage", resourceCulture);
            }
        }
        
        internal static string submit_your_members_organisation_details {
            get {
                return ResourceManager.GetString("submit_your_members_organisation_details", resourceCulture);
            }
        }
        
        internal static string yes_submit {
            get {
                return ResourceManager.GetString("yes_submit", resourceCulture);
            }
        }
        
        internal static string no_not_right_now {
            get {
                return ResourceManager.GetString("no_not_right_now", resourceCulture);
            }
        }
        
        internal static string your_org_may_face_enforcement_action_if_the_data_you_submit_is_inaccurate {
            get {
                return ResourceManager.GetString("your_org_may_face_enforcement_action_if_the_data_you_submit_is_inaccurate", resourceCulture);
            }
        }
        
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        internal static string information_will_be_sent_to_the_environmental_regulator {
            get {
                return ResourceManager.GetString("information_will_be_sent_to_the_environmental_regulator", resourceCulture);
            }
        }
        
        internal static string submit_your_organisation_details {
            get {
                return ResourceManager.GetString("submit_your_organisation_details", resourceCulture);
            }
        }
        
        internal static string check_files_and_submit {
            get {
                return ResourceManager.GetString("check_files_and_submit", resourceCulture);
            }
        }
        
        internal static string ReviewCompanyDetails_ResponseErrorMessage {
            get {
                return ResourceManager.GetString("ReviewCompanyDetails.ResponseErrorMessage", resourceCulture);
            }
        }
        
        internal static string files_to_submit {
            get {
                return ResourceManager.GetString("files_to_submit", resourceCulture);
            }
        }
        
        internal static string files_already_submitted {
            get {
                return ResourceManager.GetString("files_already_submitted", resourceCulture);
            }
        }
        
        internal static string resubmit_your_members_organisation_details {
            get {
                return ResourceManager.GetString("resubmit_your_members_organisation_details", resourceCulture);
            }
        }
        
        internal static string check_files_and_resubmit {
            get {
                return ResourceManager.GetString("check_files_and_resubmit", resourceCulture);
            }
        }
        
        internal static string yes_resubmit {
            get {
                return ResourceManager.GetString("yes_resubmit", resourceCulture);
            }
        }
        
        internal static string submitted_by {
            get {
                return ResourceManager.GetString("submitted_by", resourceCulture);
            }
        }
        
        internal static string date_submitted {
            get {
                return ResourceManager.GetString("date_submitted", resourceCulture);
            }
        }
        
        internal static string text_assistive_warning {
            get {
                return ResourceManager.GetString("text_assistive.warning", resourceCulture);
            }
        }
        
        internal static string ReviewCompanyDetails_ResponseErrorMessage_Producer {
            get {
                return ResourceManager.GetString("ReviewCompanyDetails.ResponseErrorMessage.Producer", resourceCulture);
            }
        }
        
        internal static string detail_regarding_the_latest_file_uploaded {
            get {
                return ResourceManager.GetString("detail_regarding_the_latest_file_uploaded", resourceCulture);
            }
        }
        
        internal static string detail_regarding_the_latest_file_submitted {
            get {
                return ResourceManager.GetString("detail_regarding_the_latest_file_submitted", resourceCulture);
            }
        }
    }
}
