//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.FileUploadSubLanding {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUploadSubLanding {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadSubLanding() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.FileUploadSubLanding.FileUploadSubL" +
                            "anding", typeof(FileUploadSubLanding).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string before_you_start {
            get {
                return ResourceManager.GetString("before_you_start", resourceCulture);
            }
        }
        
        internal static string read_the_guidance_on {
            get {
                return ResourceManager.GetString("read_the_guidance_on", resourceCulture);
            }
        }
        
        internal static string what_packaging_data_you_need_to_collect {
            get {
                return ResourceManager.GetString("what_packaging_data_you_need_to_collect", resourceCulture);
            }
        }
        
        internal static string how_to_build_a_csv_file_to_report_your_packaging_data {
            get {
                return ResourceManager.GetString("how_to_build_a_csv_file_to_report_your_packaging_data", resourceCulture);
            }
        }
        
        internal static string an_example_csv_file {
            get {
                return ResourceManager.GetString("an_example_csv_file", resourceCulture);
            }
        }
        
        internal static string deadline {
            get {
                return ResourceManager.GetString("deadline", resourceCulture);
            }
        }
        
        internal static string not_started {
            get {
                return ResourceManager.GetString("not_started", resourceCulture);
            }
        }
        
        internal static string file_uploaded {
            get {
                return ResourceManager.GetString("file_uploaded", resourceCulture);
            }
        }
        
        internal static string report_packaging_data_for {
            get {
                return ResourceManager.GetString("report_packaging_data_for", resourceCulture);
            }
        }
        
        internal static string start_now {
            get {
                return ResourceManager.GetString("start_now", resourceCulture);
            }
        }
        
        internal static string report_packaging_data {
            get {
                return ResourceManager.GetString("report_packaging_data", resourceCulture);
            }
        }
        
        internal static string submitted_to_regulator {
            get {
                return ResourceManager.GetString("submitted_to_regulator", resourceCulture);
            }
        }
        
        internal static string cannot_start_yet {
            get {
                return ResourceManager.GetString("cannot_start_yet", resourceCulture);
            }
        }
        
        internal static string report_members_packaging_data_for {
            get {
                return ResourceManager.GetString("report_members_packaging_data_for", resourceCulture);
            }
        }
        
        internal static string large_organisations {
            get {
                return ResourceManager.GetString("large_organisations", resourceCulture);
            }
        }
        
        internal static string check_the_govuk_guidance {
            get {
                return ResourceManager.GetString("check_the_govuk_guidance", resourceCulture);
            }
        }
        
        internal static string if_youve_missed_a_deadline {
            get {
                return ResourceManager.GetString("if_youve_missed_a_deadline", resourceCulture);
            }
        }
        
        internal static string if_youve_missed_a_deadline_to_submit {
            get {
                return ResourceManager.GetString("if_youve_missed_a_deadline_to_submit", resourceCulture);
            }
        }
    }
}
