//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.FileUploadCheckFileAndSubmit {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUploadCheckFileAndSubmit {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadCheckFileAndSubmit() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.FileUploadCheckFileAndSubmit.FileUp" +
                            "loadCheckFileAndSubmit", typeof(FileUploadCheckFileAndSubmit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string packaging_data_uploaded {
            get {
                return ResourceManager.GetString("packaging_data_uploaded", resourceCulture);
            }
        }
        
        internal static string check_and_submit_file {
            get {
                return ResourceManager.GetString("check_and_submit_file", resourceCulture);
            }
        }
        
        internal static string file_uploaded {
            get {
                return ResourceManager.GetString("file_uploaded", resourceCulture);
            }
        }
        
        internal static string file_youre_submitting {
            get {
                return ResourceManager.GetString("file_youre_submitting", resourceCulture);
            }
        }
        
        internal static string detail_regarding_the_latest_file_uploaded {
            get {
                return ResourceManager.GetString("detail_regarding_the_latest_file_uploaded", resourceCulture);
            }
        }
        
        internal static string file_name {
            get {
                return ResourceManager.GetString("file_name", resourceCulture);
            }
        }
        
        internal static string date_uploaded {
            get {
                return ResourceManager.GetString("date_uploaded", resourceCulture);
            }
        }
        
        internal static string uploaded_by {
            get {
                return ResourceManager.GetString("uploaded_by", resourceCulture);
            }
        }
        
        internal static string last_file_submitted {
            get {
                return ResourceManager.GetString("last_file_submitted", resourceCulture);
            }
        }
        
        internal static string detail_regarding_the_latest_file_submitted {
            get {
                return ResourceManager.GetString("detail_regarding_the_latest_file_submitted", resourceCulture);
            }
        }
        
        internal static string date_submitted {
            get {
                return ResourceManager.GetString("date_submitted", resourceCulture);
            }
        }
        
        internal static string submitted_by {
            get {
                return ResourceManager.GetString("submitted_by", resourceCulture);
            }
        }
        
        internal static string confirm_you_want_to_submit_the_new_packaging_data_file_to_the_environmental_regulator {
            get {
                return ResourceManager.GetString("confirm_you_want_to_submit_the_new_packaging_data_file_to_the_environmental_regul" +
                        "ator", resourceCulture);
            }
        }
        
        internal static string this_will_replace_the_last_packaging_data_file_that_you_submitted {
            get {
                return ResourceManager.GetString("this_will_replace_the_last_packaging_data_file_that_you_submitted", resourceCulture);
            }
        }
        
        internal static string are_you_sure_you_want_to_submit_your_packaging_data_file {
            get {
                return ResourceManager.GetString("are_you_sure_you_want_to_submit_your_packaging_data_file", resourceCulture);
            }
        }
        
        internal static string this_information_will_be_sent_to_the_environmental_regulator {
            get {
                return ResourceManager.GetString("this_information_will_be_sent_to_the_environmental_regulator", resourceCulture);
            }
        }
        
        internal static string yes_id_like_to_submit {
            get {
                return ResourceManager.GetString("yes_id_like_to_submit", resourceCulture);
            }
        }
        
        internal static string no_i_dont_want_to_do_this_right_now {
            get {
                return ResourceManager.GetString("no_i_dont_want_to_do_this_right_now", resourceCulture);
            }
        }
        
        internal static string your_company_may_face_enforcement_action_if_the_data_you_submit_is_inaccurate {
            get {
                return ResourceManager.GetString("your_company_may_face_enforcement_action_if_the_data_you_submit_is_inaccurate", resourceCulture);
            }
        }
        
        internal static string how_to_submit_your_file {
            get {
                return ResourceManager.GetString("how_to_submit_your_file", resourceCulture);
            }
        }
        
        internal static string you_dont_have_permission_to_submit_files {
            get {
                return ResourceManager.GetString("you_dont_have_permission_to_submit_files", resourceCulture);
            }
        }
        
        internal static string someone_in_your_team_with_the_right_account_permissions_must_submit_these_file_to_the_environmental_regulator {
            get {
                return ResourceManager.GetString("someone_in_your_team_with_the_right_account_permissions_must_submit_these_file_to" +
                        "_the_environmental_regulator", resourceCulture);
            }
        }
        
        internal static string go_to_your_account_homepage {
            get {
                return ResourceManager.GetString("go_to_your_account_homepage", resourceCulture);
            }
        }
    }
}
