//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.FileUploadCheckFileAndSubmit {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUploadCheckFileAndSubmit {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadCheckFileAndSubmit() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.FileUploadCheckFileAndSubmit.FileUp" +
                            "loadCheckFileAndSubmit", typeof(FileUploadCheckFileAndSubmit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string check_and_submit_file {
            get {
                return ResourceManager.GetString("check_and_submit_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string date_and_time_submitted {
            get {
                return ResourceManager.GetString("date_and_time_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string date_and_time_uploaded {
            get {
                return ResourceManager.GetString("date_and_time_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string detail_regarding_the_latest_file_submitted {
            get {
                return ResourceManager.GetString("detail_regarding_the_latest_file_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string detail_regarding_the_latest_file_uploaded {
            get {
                return ResourceManager.GetString("detail_regarding_the_latest_file_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string download {
            get {
                return ResourceManager.GetString("download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string file_name {
            get {
                return ResourceManager.GetString("file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string file_uploaded {
            get {
                return ResourceManager.GetString("file_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string file_youre_submitting {
            get {
                return ResourceManager.GetString("file_youre_submitting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string go_to_your_account_homepage {
            get {
                return ResourceManager.GetString("go_to_your_account_homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string how_to_submit_your_file {
            get {
                return ResourceManager.GetString("how_to_submit_your_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string last_file_submitted {
            get {
                return ResourceManager.GetString("last_file_submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string once_you_have_submitted_your_new_files_you_can_only_make_changes_after_the_environmental_regulator_has_looked_at_them {
            get {
                return ResourceManager.GetString("once_you_have_submitted_your_new_files_you_can_only_make_changes_after_the_enviro" +
                        "nmental_regulator_has_looked_at_them", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string packaging_data_uploaded {
            get {
                return ResourceManager.GetString("packaging_data_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string someone_in_your_team_with_the_right_account_permissions_must_submit_these_file_to_the_environmental_regulator {
            get {
                return ResourceManager.GetString("someone_in_your_team_with_the_right_account_permissions_must_submit_these_file_to" +
                        "_the_environmental_regulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string submitted_by {
            get {
                return ResourceManager.GetString("submitted_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string submitting_the_new_packaging_data_file_will_replace_the_last_one_that_you_submitted {
            get {
                return ResourceManager.GetString("submitting_the_new_packaging_data_file_will_replace_the_last_one_that_you_submitt" +
                        "ed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string the_file_youve_uploaded_has_saved {
            get {
                return ResourceManager.GetString("the_file_youve_uploaded_has_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string uploaded_by {
            get {
                return ResourceManager.GetString("uploaded_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string you_dont_have_permission_to_submit_files {
            get {
                return ResourceManager.GetString("you_dont_have_permission_to_submit_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string your_company_may_face_enforcement_action_if_the_data_you_submit_is_inaccurate {
            get {
                return ResourceManager.GetString("your_company_may_face_enforcement_action_if_the_data_you_submit_is_inaccurate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string your_file_has_saved_and_you_can_submit_it_to_the_environmental_regulator {
            get {
                return ResourceManager.GetString("your_file_has_saved_and_you_can_submit_it_to_the_environmental_regulator", resourceCulture);
            }
        }
    }
}
