//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.FileUploadWarning {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUploadWarning {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadWarning() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.FileUploadWarning.FileUploadWarning" +
                            "", typeof(FileUploadWarning).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string check_the_warnings {
            get {
                return ResourceManager.GetString("check_the_warnings", resourceCulture);
            }
        }
        
        internal static string your_data_file_has_been_uploaded {
            get {
                return ResourceManager.GetString("your_data_file_has_been_uploaded", resourceCulture);
            }
        }
        
        internal static string there_are_some_warnings {
            get {
                return ResourceManager.GetString("there_are_some_warnings", resourceCulture);
            }
        }
        
        internal static string download_warning_report {
            get {
                return ResourceManager.GetString("download_warning_report", resourceCulture);
            }
        }
        
        internal static string tells_you_where_warnings_are {
            get {
                return ResourceManager.GetString("tells_you_where_warnings_are", resourceCulture);
            }
        }
        
        internal static string we_can_only_show_x_warnings {
            get {
                return ResourceManager.GetString("we_can_only_show_x_warnings", resourceCulture);
            }
        }
        
        internal static string how_to_check_warnings {
            get {
                return ResourceManager.GetString("how_to_check_warnings", resourceCulture);
            }
        }
        
        internal static string use_the_report_to_check_warnings {
            get {
                return ResourceManager.GetString("use_the_report_to_check_warnings", resourceCulture);
            }
        }
        
        internal static string file_specification_guidance {
            get {
                return ResourceManager.GetString("file_specification_guidance", resourceCulture);
            }
        }
        
        internal static string decide_if_you_want_to_update {
            get {
                return ResourceManager.GetString("decide_if_you_want_to_update", resourceCulture);
            }
        }
        
        internal static string upload_new_file_or_keep {
            get {
                return ResourceManager.GetString("upload_new_file_or_keep", resourceCulture);
            }
        }
        
        internal static string do_you_want_to_upload_a_new_file {
            get {
                return ResourceManager.GetString("do_you_want_to_upload_a_new_file", resourceCulture);
            }
        }
        
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
        
        internal static string no_keep_this_file_uploaded {
            get {
                return ResourceManager.GetString("no_keep_this_file_uploaded", resourceCulture);
            }
        }
    }
}
