//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CompanyDetailsSubmissionErrorCodes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CompanyDetailsSubmissionErrorCodes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.CompanyDetailsSubmissionErrorCodes", typeof(CompanyDetailsSubmissionErrorCodes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid File Format.
        /// </summary>
        internal static string _80 {
            get {
                return ResourceManager.GetString("80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the organisation ID.
        /// </summary>
        internal static string _801 {
            get {
                return ResourceManager.GetString("801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the organisation name.
        /// </summary>
        internal static string _802 {
            get {
                return ResourceManager.GetString("802", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the home nation code.
        /// </summary>
        internal static string _803 {
            get {
                return ResourceManager.GetString("803", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home nation code must be one of EN NI SC or WS.
        /// </summary>
        internal static string _804 {
            get {
                return ResourceManager.GetString("804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the first name of the primary contact.
        /// </summary>
        internal static string _805 {
            get {
                return ResourceManager.GetString("805", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the last name of the primary contact.
        /// </summary>
        internal static string _806 {
            get {
                return ResourceManager.GetString("806", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the email of the primary contact.
        /// </summary>
        internal static string _807 {
            get {
                return ResourceManager.GetString("807", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone number of the primary contact.
        /// </summary>
        internal static string _808 {
            get {
                return ResourceManager.GetString("808", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the first line of the registered address.
        /// </summary>
        internal static string _809 {
            get {
                return ResourceManager.GetString("809", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the postcode for the registered address.
        /// </summary>
        internal static string _810 {
            get {
                return ResourceManager.GetString("810", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone number for the registered address.
        /// </summary>
        internal static string _811 {
            get {
                return ResourceManager.GetString("811", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enter an audit address the country must be one of the following: EN, NI, SC, WS, UK, GB, England, Northern Ireland, Scotland, Wales, United Kingdom or Great Britain.
        /// </summary>
        internal static string _812 {
            get {
                return ResourceManager.GetString("812", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enter an audit address, it must include the first line of the address.
        /// </summary>
        internal static string _814 {
            get {
                return ResourceManager.GetString("814", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enter an audit address, it must include the postcode.
        /// </summary>
        internal static string _815 {
            get {
                return ResourceManager.GetString("815", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the first line of the principal address.
        /// </summary>
        internal static string _816 {
            get {
                return ResourceManager.GetString("816", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the postcode for the principal address.
        /// </summary>
        internal static string _817 {
            get {
                return ResourceManager.GetString("817", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the phone number for the principal address.
        /// </summary>
        internal static string _818 {
            get {
                return ResourceManager.GetString("818", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot repeat combination of organisation ID and subsidiary ID.
        /// </summary>
        internal static string _819 {
            get {
                return ResourceManager.GetString("819", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Csv File Is Empty.
        /// </summary>
        internal static string _82 {
            get {
                return ResourceManager.GetString("82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIC code must be a 5 digit number - include zeros at the start if needed.
        /// </summary>
        internal static string _820 {
            get {
                return ResourceManager.GetString("820", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisations must have one Primary packaging activity.
        /// </summary>
        internal static string _821 {
            get {
                return ResourceManager.GetString("821", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisations cannot have more than one Primary packaging activity.
        /// </summary>
        internal static string _822 {
            get {
                return ResourceManager.GetString("822", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging activity can only be Primary Secondary or No.
        /// </summary>
        internal static string _823 {
            get {
                return ResourceManager.GetString("823", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the packaging activity - supplied under own brand.
        /// </summary>
        internal static string _824 {
            get {
                return ResourceManager.GetString("824", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the packaging activity - packed or filled as unbranded.
        /// </summary>
        internal static string _825 {
            get {
                return ResourceManager.GetString("825", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the packaging activity - imported.
        /// </summary>
        internal static string _826 {
            get {
                return ResourceManager.GetString("826", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the packaging activity - supplied as empty.
        /// </summary>
        internal static string _827 {
            get {
                return ResourceManager.GetString("827", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the packaging activity - hired or loaned.
        /// </summary>
        internal static string _828 {
            get {
                return ResourceManager.GetString("828", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the packaging activity - supplied through an online marketplace owned by the organisation.
        /// </summary>
        internal static string _829 {
            get {
                return ResourceManager.GetString("829", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Headers.
        /// </summary>
        internal static string _83 {
            get {
                return ResourceManager.GetString("83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the packaging activity - selling.
        /// </summary>
        internal static string _830 {
            get {
                return ResourceManager.GetString("830", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Yes or No - does the organisation put packaging on the market which has no brand names, identifying marks or trademarks?.
        /// </summary>
        internal static string _831 {
            get {
                return ResourceManager.GetString("831", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trading name must be different from organisation name.
        /// </summary>
        internal static string _840 {
            get {
                return ResourceManager.GetString("840", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enter a service address, it must include the first line of the address.
        /// </summary>
        internal static string _845 {
            get {
                return ResourceManager.GetString("845", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enter a service address, it must include the postcode.
        /// </summary>
        internal static string _846 {
            get {
                return ResourceManager.GetString("846", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you enter a service address, it must include the phone number.
        /// </summary>
        internal static string _847 {
            get {
                return ResourceManager.GetString("847", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation sub type is  LIC POB FRA - this means you must enter details of another organisation with a sub type of LFR TEN or OTH.
        /// </summary>
        internal static string _848 {
            get {
                return ResourceManager.GetString("848", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnover must not include a comma.
        /// </summary>
        internal static string _855 {
            get {
                return ResourceManager.GetString("855", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnover must be in millions to two decimal places.
        /// </summary>
        internal static string _856 {
            get {
                return ResourceManager.GetString("856", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnover must be greater than 0&quot; - this one applies if the user has entered 0, or a negative integer.
        /// </summary>
        internal static string _857 {
            get {
                return ResourceManager.GetString("857", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turnover must only include numbers.
        /// </summary>
        internal static string _858 {
            get {
                return ResourceManager.GetString("858", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies House number cannot be 00000000.
        /// </summary>
        internal static string _859 {
            get {
                return ResourceManager.GetString("859", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies House number not needed for this organisation type.
        /// </summary>
        internal static string _860 {
            get {
                return ResourceManager.GetString("860", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Companies House number does not match this organisation ID - check both.
        /// </summary>
        internal static string _861 {
            get {
                return ResourceManager.GetString("861", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total tonnage must be greater than 0&quot; - this one applies if the user has entered 0, or a negative integer.
        /// </summary>
        internal static string _865 {
            get {
                return ResourceManager.GetString("865", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total tonnage must not include a comma.
        /// </summary>
        internal static string _867 {
            get {
                return ResourceManager.GetString("867", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total tonnage must only include numbers.
        /// </summary>
        internal static string _868 {
            get {
                return ResourceManager.GetString("868", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the organisation type code.
        /// </summary>
        internal static string _880 {
            get {
                return ResourceManager.GetString("880", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation type code must be one of SOL PAR REG PLC LLP LTD LPA COP CIC OUT OTH.
        /// </summary>
        internal static string _881 {
            get {
                return ResourceManager.GetString("881", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check organisation ID - this one is either invalid or for an organisation that does not need to submit data.
        /// </summary>
        internal static string _882 {
            get {
                return ResourceManager.GetString("882", resourceCulture);
            }
        }
    }
}
