//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ErrorMessages {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string privacy_policy_not_approved {
            get {
                return ResourceManager.GetString("privacy_policy_not_approved", resourceCulture);
            }
        }
        
        internal static string declaration_not_approved {
            get {
                return ResourceManager.GetString("declaration_not_approved", resourceCulture);
            }
        }
        
        internal static string select_yes_if_you_want_to_submit_your_packaging_data {
            get {
                return ResourceManager.GetString("select_yes_if_you_want_to_submit_your_packaging_data", resourceCulture);
            }
        }
        
        internal static string declaration_name_required_key {
            get {
                return ResourceManager.GetString("declaration_name_required_key", resourceCulture);
            }
        }
        
        internal static string declaration_name_max_length_key {
            get {
                return ResourceManager.GetString("declaration_name_max_length_key", resourceCulture);
            }
        }
        
        internal static string using_compliance_scheme_selection_error {
            get {
                return ResourceManager.GetString("using_compliance_scheme_selection_error", resourceCulture);
            }
        }
        
        internal static string select_which_compliance_error {
            get {
                return ResourceManager.GetString("select_which_compliance_error", resourceCulture);
            }
        }
        
        internal static string select_whether_youve_changed_compliance_scheme {
            get {
                return ResourceManager.GetString("select_whether_youve_changed_compliance_scheme", resourceCulture);
            }
        }
        
        internal static string Select_yes_if_you_would_like_to_remove_this_member_from_your_account {
            get {
                return ResourceManager.GetString("Select_yes_if_you_would_like_to_remove_this_member_from_your_account", resourceCulture);
            }
        }
        
        internal static string select_yes_if_you_want_to_upload_a_new_file {
            get {
                return ResourceManager.GetString("select_yes_if_you_want_to_upload_a_new_file", resourceCulture);
            }
        }
    }
}
