//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SharedResources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string back {
            get {
                return ResourceManager.GetString("back", resourceCulture);
            }
        }
        
        internal static string confirm_and_continue {
            get {
                return ResourceManager.GetString("confirm_and_continue", resourceCulture);
            }
        }
        
        internal static string manage_account {
            get {
                return ResourceManager.GetString("manage_account", resourceCulture);
            }
        }
        
        internal static string sign_out {
            get {
                return ResourceManager.GetString("sign_out", resourceCulture);
            }
        }
        
        internal static string there_is_a_problem {
            get {
                return ResourceManager.GetString("there_is_a_problem", resourceCulture);
            }
        }
        
        internal static string skip_to_main_content_text {
            get {
                return ResourceManager.GetString("skip_to_main_content_text", resourceCulture);
            }
        }
        
        internal static string go_to_account_home_page {
            get {
                return ResourceManager.GetString("go_to_account_home_page", resourceCulture);
            }
        }
        
        internal static string _continue {
            get {
                return ResourceManager.GetString("continue", resourceCulture);
            }
        }
        
        internal static string application_title {
            get {
                return ResourceManager.GetString("application_title", resourceCulture);
            }
        }
        
        internal static string home {
            get {
                return ResourceManager.GetString("home", resourceCulture);
            }
        }
        
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        internal static string manage_account_details {
            get {
                return ResourceManager.GetString("manage_account_details", resourceCulture);
            }
        }
        
        internal static string the_file_may_take_a_few_minutes_to_upload {
            get {
                return ResourceManager.GetString("the_file_may_take_a_few_minutes_to_upload", resourceCulture);
            }
        }
        
        internal static string do_not_close_the_window_while_the_file_is_uploading {
            get {
                return ResourceManager.GetString("do_not_close_the_window_while_the_file_is_uploading", resourceCulture);
            }
        }
        
        internal static string change {
            get {
                return ResourceManager.GetString("change", resourceCulture);
            }
        }
        
        internal static string warning {
            get {
                return ResourceManager.GetString("warning", resourceCulture);
            }
        }
        
        internal static string Cymraeg {
            get {
                return ResourceManager.GetString("Cymraeg", resourceCulture);
            }
        }
        
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        internal static string Welsh {
            get {
                return ResourceManager.GetString("Welsh", resourceCulture);
            }
        }
        
        internal static string January_to_June_2023 {
            get {
                return ResourceManager.GetString("January to June 2023", resourceCulture);
            }
        }
        
        internal static string July_to_December_2023 {
            get {
                return ResourceManager.GetString("July to December 2023", resourceCulture);
            }
        }
        
        internal static string sorry_problem_service {
            get {
                return ResourceManager.GetString("sorry_problem_service", resourceCulture);
            }
        }
        
        internal static string try_again_later {
            get {
                return ResourceManager.GetString("try_again_later", resourceCulture);
            }
        }
        
        internal static string scheme_members {
            get {
                return ResourceManager.GetString("scheme_members", resourceCulture);
            }
        }
        
        internal static string defra {
            get {
                return ResourceManager.GetString("defra", resourceCulture);
            }
        }
        
        internal static string member_details {
            get {
                return ResourceManager.GetString("member_details", resourceCulture);
            }
        }
        
        internal static string next_page {
            get {
                return ResourceManager.GetString("next_page", resourceCulture);
            }
        }
        
        internal static string menu {
            get {
                return ResourceManager.GetString("menu", resourceCulture);
            }
        }
        
        internal static string hidden_error {
            get {
                return ResourceManager.GetString("hidden_error", resourceCulture);
            }
        }
        
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        internal static string confirm {
            get {
                return ResourceManager.GetString("confirm", resourceCulture);
            }
        }
        
        internal static string upload_a_file {
            get {
                return ResourceManager.GetString("upload_a_file", resourceCulture);
            }
        }
        
        internal static string sign_in {
            get {
                return ResourceManager.GetString("sign_in", resourceCulture);
            }
        }
    }
}
