trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'src/*'
      - 'tools/**'

parameters:

  - name: sonarqubeInstance
    displayName: 'Select SonarQube version'
    type: string
    default: 'SonarQube'
    values:
    - 'SonarQube'
    # - 'SonarQubeLatest'

  - name: runIntegrationTests
    displayName: 'Run integration tests'
    type: boolean
    default: true


pool: DEFRA-COMMON-UBUNTU-SSV3

variables:
  - template: vars/DEV4-development.yaml
  - name: solutionFolder
    value: src
  - name: projectFolder
    value: FrontendSchemeRegistration.UI
  - name: testProjectFolder
    value: FrontendSchemeRegistration.UI.UnitTests
  - name: testPattern
    value: |
      src/*[Uu]nit[Tt]ests/*.csproj
      tools/translations/Translations.UnitTests/Translations.UnitTests.csproj
  - name: sonarQubeProjectKey
    value: epr-packaging-frontend
  - name: sonarQubeProjectName
    value: epr-packaging-frontend
  - name: runTests
    value: true
  - name: runNugetTasks
    value: true
  - name: dotnetVersion
    value: dotnetVersion10

resources:
  repositories:
    - repository: CommonTemplates
      name: defra/epr-webapps-code-deploy-templates
      type: github
      endpoint: defra
      ref: main

extends:
  template: epr-build-pipeline.yaml@CommonTemplates
  parameters:
    solutionFolder: ${{ variables.solutionFolder }}
    projectFolder: ${{ variables.projectFolder }}
    testProjectFolder: ${{ variables.testProjectFolder }}
    testPattern: ${{ variables.testPattern }}
    sonarQubeProjectKey: ${{ variables.sonarQubeProjectKey }}
    sonarQubeProjectName: ${{ variables.sonarQubeProjectName }}
    runTests: ${{ variables.runTests }}
    runIntegrationTests: ${{ parameters.runIntegrationTests }}
    azureSubscription: $(azureSubscription)
    acrAzureContainerRegistryName: $(acr.azureContainerRegistryName)
    acrRepositoryName: $(acr.repositoryName)
    branchName: ${{ replace(replace(variables['Build.SourceBranch'], 'refs/heads/', ''), '/', '_') }}
    runNugetTasks: ${{ variables.runNugetTasks }}
    serviceName: $(serviceName)
    dotnetVersion: ${{ variables.dotnetVersion }}
    sonarqubeInstance: ${{ parameters.sonarqubeInstance }}
