//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.DelegatedPerson {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class InviteChangePermissions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InviteChangePermissions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.DelegatedPerson.InviteChangePermissions", typeof(InviteChangePermissions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Title {
            get {
                return ResourceManager.GetString("InviteChangePermissions.Title", resourceCulture);
            }
        }
        
        internal static string Question {
            get {
                return ResourceManager.GetString("InviteChangePermissions.Question", resourceCulture);
            }
        }
        
        internal static string InvitedToChangePermissions {
            get {
                return ResourceManager.GetString("InviteChangePermissions.InvitedToChangePermissions", resourceCulture);
            }
        }
        
        internal static string YouNeedToAccept {
            get {
                return ResourceManager.GetString("InviteChangePermissions.YouNeedToAccept", resourceCulture);
            }
        }
        
        internal static string HowLongItTakes {
            get {
                return ResourceManager.GetString("InviteChangePermissions.HowLongItTakes", resourceCulture);
            }
        }
        
        internal static string ItCanTakeUpTo {
            get {
                return ResourceManager.GetString("InviteChangePermissions.ItCanTakeUpTo", resourceCulture);
            }
        }
        
        internal static string OnceTheyApprove {
            get {
                return ResourceManager.GetString("InviteChangePermissions.OnceTheyApprove", resourceCulture);
            }
        }
    }
}
