//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.PrivacyPolicy {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PrivacyPolicy {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PrivacyPolicy() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.PrivacyPolicy.PrivacyPolicy", typeof(PrivacyPolicy).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string confirm_privacy_policy {
            get {
                return ResourceManager.GetString("confirm_privacy_policy", resourceCulture);
            }
        }
        
        internal static string key_points {
            get {
                return ResourceManager.GetString("key_points", resourceCulture);
            }
        }
        
        internal static string key_point_1 {
            get {
                return ResourceManager.GetString("key_point_1", resourceCulture);
            }
        }
        
        internal static string key_point_2 {
            get {
                return ResourceManager.GetString("key_point_2", resourceCulture);
            }
        }
        
        internal static string key_point_3 {
            get {
                return ResourceManager.GetString("key_point_3", resourceCulture);
            }
        }
        
        internal static string privacy_policy_not_approved {
            get {
                return ResourceManager.GetString("privacy_policy_not_approved", resourceCulture);
            }
        }
        
        internal static string read_privacy_policy {
            get {
                return ResourceManager.GetString("read_privacy_policy", resourceCulture);
            }
        }
        
        internal static string review {
            get {
                return ResourceManager.GetString("review", resourceCulture);
            }
        }
    }
}
