//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.FileUploadCompanyDetails {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUploadCompanyDetails {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadCompanyDetails() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.FileUploadCompanyDetails.FileUpload" +
                            "CompanyDetails", typeof(FileUploadCompanyDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string upload_organisation_details {
            get {
                return ResourceManager.GetString("upload_organisation_details", resourceCulture);
            }
        }
        
        internal static string when_you_submit_an_organisation_s_packaging_data_you_also_need_to {
            get {
                return ResourceManager.GetString("when_you_submit_an_organisation_s_packaging_data_you_also_need_to", resourceCulture);
            }
        }
        
        internal static string organisation_details_include_things_like {
            get {
                return ResourceManager.GetString("organisation_details_include_things_like", resourceCulture);
            }
        }
        
        internal static string address {
            get {
                return ResourceManager.GetString("address", resourceCulture);
            }
        }
        
        internal static string turnover {
            get {
                return ResourceManager.GetString("turnover", resourceCulture);
            }
        }
        
        internal static string packaging_activities {
            get {
                return ResourceManager.GetString("packaging_activities", resourceCulture);
            }
        }
        
        internal static string you_may_also_need_to_report_an_organisation_s {
            get {
                return ResourceManager.GetString("you_may_also_need_to_report_an_organisation_s", resourceCulture);
            }
        }
        
        internal static string brand_activities_if_they_supply_goods_to_the_uk_market_in_primary {
            get {
                return ResourceManager.GetString("brand_activities_if_they_supply_goods_to_the_uk_market_in_primary", resourceCulture);
            }
        }
        
        internal static string partners_if_they_re_registered_as_a_partnership_in_companies_house {
            get {
                return ResourceManager.GetString("partners_if_they_re_registered_as_a_partnership_in_companies_house", resourceCulture);
            }
        }
        
        internal static string once_you_submit_these_details_the_organisation_is_officially_registered {
            get {
                return ResourceManager.GetString("once_you_submit_these_details_the_organisation_is_officially_registered", resourceCulture);
            }
        }
        
        internal static string upload_file {
            get {
                return ResourceManager.GetString("upload_file", resourceCulture);
            }
        }
        
        internal static string upload_organisation_details_to_your_account {
            get {
                return ResourceManager.GetString("upload_organisation_details_to_your_account", resourceCulture);
            }
        }
        
        internal static string upload_the_organisation_details_in_a_csv_file {
            get {
                return ResourceManager.GetString("upload_the_organisation_details_in_a_csv_file", resourceCulture);
            }
        }
        
        internal static string based_on_whats_in_the_organisation {
            get {
                return ResourceManager.GetString("based_on_whats_in_the_organisation", resourceCulture);
            }
        }
    }
}
