//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Views.FileUploadCompanyDetails {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUploadCompanyDetailsCso {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadCompanyDetailsCso() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.FileUploadCompanyDetails.FileUpload" +
                            "CompanyDetailsCso", typeof(FileUploadCompanyDetailsCso).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string you_should {
            get {
                return ResourceManager.GetString("you_should", resourceCulture);
            }
        }
        
        internal static string all_files_ready {
            get {
                return ResourceManager.GetString("all_files_ready", resourceCulture);
            }
        }
        
        internal static string ensure_file_format {
            get {
                return ResourceManager.GetString("ensure_file_format", resourceCulture);
            }
        }
        
        internal static string include_information {
            get {
                return ResourceManager.GetString("include_information", resourceCulture);
            }
        }
        
        internal static string available_document_template {
            get {
                return ResourceManager.GetString("available_document_template", resourceCulture);
            }
        }
        
        internal static string file_rejected {
            get {
                return ResourceManager.GetString("file_rejected", resourceCulture);
            }
        }
        
        internal static string large_producer_detail {
            get {
                return ResourceManager.GetString("large_producer_detail", resourceCulture);
            }
        }
        
        internal static string subsidiaries_guidance {
            get {
                return ResourceManager.GetString("subsidiaries_guidance", resourceCulture);
            }
        }
        
        internal static string manage_your_subsidiaries {
            get {
                return ResourceManager.GetString("manage_your_subsidiaries", resourceCulture);
            }
        }
        
        internal static string file_upload_warning {
            get {
                return ResourceManager.GetString("file_upload_warning", resourceCulture);
            }
        }
        
        internal static string register_company_size {
            get {
                return ResourceManager.GetString("register_company_size", resourceCulture);
            }
        }
        
        internal static string report_your_organisation_detail {
            get {
                return ResourceManager.GetString("report_your_organisation_detail", resourceCulture);
            }
        }
        
        internal static string report_your_member_organisation_detail {
            get {
                return ResourceManager.GetString("report_your_member_organisation_detail", resourceCulture);
            }
        }
        
        internal static string upload_organisation_details {
            get {
                return ResourceManager.GetString("upload_organisation_details", resourceCulture);
            }
        }
    }
}
