variables:
  azureSubscription: 'AZR-RWD-PRD1'
  docker.imageName: 'eprpackagingfrontend'
  acr.azureContainerRegistryName: 'prdrwdinfac1401'
  acr.repositoryName: 'eprpackagingfrontendrepository'
  serviceName: 'prdrwdwebwa1410'
