//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.FileUploadCompanyDetailsSuccess {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class FileUploadCompanyDetailsSuccess {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FileUploadCompanyDetailsSuccess() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.FileUploadCompanyDetailsSuccess.Fil" +
                            "eUploadCompanyDetailsSuccess", typeof(FileUploadCompanyDetailsSuccess).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string upload_company_details_completed {
            get {
                return ResourceManager.GetString("upload_company_details_completed", resourceCulture);
            }
        }
        
        internal static string success {
            get {
                return ResourceManager.GetString("success", resourceCulture);
            }
        }
        
        internal static string organisation_details_updated {
            get {
                return ResourceManager.GetString("organisation_details_updated", resourceCulture);
            }
        }
        
        internal static string if_you_think_this_is_incorrect_you_can {
            get {
                return ResourceManager.GetString("if_you_think_this_is_incorrect_you_can", resourceCulture);
            }
        }
        
        internal static string re_upload_your_organisation_details {
            get {
                return ResourceManager.GetString("re_upload_your_organisation_details", resourceCulture);
            }
        }
        
        internal static string what_happens_next {
            get {
                return ResourceManager.GetString("what_happens_next", resourceCulture);
            }
        }
        
        internal static string brand_information {
            get {
                return ResourceManager.GetString("brand_information", resourceCulture);
            }
        }
        
        internal static string based_on_what_is_in_the_file_you_also_need_to_report_brand_information {
            get {
                return ResourceManager.GetString("based_on_what_is_in_the_file_you_also_need_to_report_brand_information", resourceCulture);
            }
        }
        
        internal static string based_on_what_is_in_the_file_you_also_need_to_report_partner_information {
            get {
                return ResourceManager.GetString("based_on_what_is_in_the_file_you_also_need_to_report_partner_information", resourceCulture);
            }
        }
        
        internal static string upload_brand_information {
            get {
                return ResourceManager.GetString("upload_brand_information", resourceCulture);
            }
        }
        
        internal static string upload_partner_information {
            get {
                return ResourceManager.GetString("upload_partner_information", resourceCulture);
            }
        }
        
        internal static string based_on_what {
            get {
                return ResourceManager.GetString("based_on_what", resourceCulture);
            }
        }
        
        internal static string you_do_not_need_to_report_information {
            get {
                return ResourceManager.GetString("you_do_not_need_to_report_information", resourceCulture);
            }
        }
        
        internal static string you_also_need_to_report_about {
            get {
                return ResourceManager.GetString("you_also_need_to_report_about", resourceCulture);
            }
        }
        
        internal static string you_can_now_see {
            get {
                return ResourceManager.GetString("you_can_now_see", resourceCulture);
            }
        }
        
        internal static string partners {
            get {
                return ResourceManager.GetString("partners", resourceCulture);
            }
        }
        
        internal static string you_do_not_need_to_report_partner_information {
            get {
                return ResourceManager.GetString("you_do_not_need_to_report_partner_information", resourceCulture);
            }
        }
        
        internal static string you_do_not_need_to_report_brand_information {
            get {
                return ResourceManager.GetString("you_do_not_need_to_report_brand_information", resourceCulture);
            }
        }
        
        internal static string the_file_has {
            get {
                return ResourceManager.GetString("the_file_has", resourceCulture);
            }
        }
        
        internal static string of_your_members {
            get {
                return ResourceManager.GetString("of_your_members", resourceCulture);
            }
        }
    }
}
