//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.DeclarationWithFullName {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DeclarationWithFullName {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DeclarationWithFullName() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.DeclarationWithFullName.Declaration" +
                            "WithFullName", typeof(DeclarationWithFullName).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string declaration {
            get {
                return ResourceManager.GetString("declaration", resourceCulture);
            }
        }
        
        internal static string by_entering_your_name {
            get {
                return ResourceManager.GetString("by_entering_your_name", resourceCulture);
            }
        }
        
        internal static string you_can_act_on_behalf {
            get {
                return ResourceManager.GetString("you_can_act_on_behalf", resourceCulture);
            }
        }
        
        internal static string the_data_you_are_submitting {
            get {
                return ResourceManager.GetString("the_data_you_are_submitting", resourceCulture);
            }
        }
        
        internal static string enter_your_full_name {
            get {
                return ResourceManager.GetString("enter_your_full_name", resourceCulture);
            }
        }
        
        internal static string may_face_enforcement {
            get {
                return ResourceManager.GetString("may_face_enforcement", resourceCulture);
            }
        }
        
        internal static string submit_file {
            get {
                return ResourceManager.GetString("submit_file", resourceCulture);
            }
        }
        
        internal static string full_name_error_message_enter_your_full_name {
            get {
                return ResourceManager.GetString("full_name_error_message.enter_your_full_name", resourceCulture);
            }
        }
        
        internal static string full_name_error_message_less_than_200 {
            get {
                return ResourceManager.GetString("full_name_error_message.less_than_200", resourceCulture);
            }
        }
        
        internal static string text_assistive_warning {
            get {
                return ResourceManager.GetString("text_assistive.warning", resourceCulture);
            }
        }
        
        internal static string cso_act_on_behalf {
            get {
                return ResourceManager.GetString("cso_act_on_behalf", resourceCulture);
            }
        }
        
        internal static string cso_enforcement_warning {
            get {
                return ResourceManager.GetString("cso_enforcement_warning", resourceCulture);
            }
        }
    }
}
