//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.UploadNewFileToSubmit {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UploadNewFileToSubmit {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadNewFileToSubmit() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.UploadNewFileToSubmit.UploadNewFile" +
                            "ToSubmit", typeof(UploadNewFileToSubmit).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string upload_new_file_to_submit_to_environmental_regulator {
            get {
                return ResourceManager.GetString("upload_new_file_to_submit_to_environmental_regulator", resourceCulture);
            }
        }
        
        internal static string re_upload_packaging_data {
            get {
                return ResourceManager.GetString("re_upload_packaging_data", resourceCulture);
            }
        }
        
        internal static string you_already_submitted_a_file {
            get {
                return ResourceManager.GetString("you_already_submitted_a_file", resourceCulture);
            }
        }
        
        internal static string your_organisation_already_submitted_a_file {
            get {
                return ResourceManager.GetString("your_organisation_already_submitted_a_file", resourceCulture);
            }
        }
        
        internal static string someone_in_your_team_will_need_to_submit_the_file {
            get {
                return ResourceManager.GetString("someone_in_your_team_will_need_to_submit_the_file", resourceCulture);
            }
        }
        
        internal static string you_have_already_uploaded_your_members_packaging_data {
            get {
                return ResourceManager.GetString("you_have_already_uploaded_your_members_packaging_data", resourceCulture);
            }
        }
        
        internal static string you_can_upload_this_information_again {
            get {
                return ResourceManager.GetString("you_can_upload_this_information_again", resourceCulture);
            }
        }
        
        internal static string someone_in_your_team_will_need_to_submit_this_information {
            get {
                return ResourceManager.GetString("someone_in_your_team_will_need_to_submit_this_information", resourceCulture);
            }
        }
        
        internal static string file_already_submitted {
            get {
                return ResourceManager.GetString("file_already_submitted", resourceCulture);
            }
        }
        
        internal static string file_already_uploaded {
            get {
                return ResourceManager.GetString("file_already_uploaded", resourceCulture);
            }
        }
        
        internal static string file_name {
            get {
                return ResourceManager.GetString("file_name", resourceCulture);
            }
        }
        
        internal static string date_submitted {
            get {
                return ResourceManager.GetString("date_submitted", resourceCulture);
            }
        }
        
        internal static string date_uploaded {
            get {
                return ResourceManager.GetString("date_uploaded", resourceCulture);
            }
        }
        
        internal static string submitted_by {
            get {
                return ResourceManager.GetString("submitted_by", resourceCulture);
            }
        }
        
        internal static string uploaded_by {
            get {
                return ResourceManager.GetString("uploaded_by", resourceCulture);
            }
        }
        
        internal static string upload_new_file {
            get {
                return ResourceManager.GetString("upload_new_file", resourceCulture);
            }
        }
        
        internal static string you_already_submitted_a_file_you_also_have_a_file_saved {
            get {
                return ResourceManager.GetString("you_already_submitted_a_file_you_also_have_a_file_saved", resourceCulture);
            }
        }
        
        internal static string your_organisation_already_submitted_a_file_you_also_have_file_saved {
            get {
                return ResourceManager.GetString("your_organisation_already_submitted_a_file_you_also_have_file_saved", resourceCulture);
            }
        }
    }
}
