//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FrontendSchemeRegistration.UI.Resources.Views.UploadingOrganisationDetails {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UploadingOrganisationDetails {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadingOrganisationDetails() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("FrontendSchemeRegistration.UI.Resources.Views.UploadingOrganisationDetails.Upload" +
                            "ingOrganisationDetails", typeof(UploadingOrganisationDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string do_not_close_the_page_and_do_not_refresh {
            get {
                return ResourceManager.GetString("do_not_close_the_page_and_do_not_refresh", resourceCulture);
            }
        }
        
        internal static string it_may_take_a_few_minutes_do_not_close_the_page {
            get {
                return ResourceManager.GetString("it_may_take_a_few_minutes_do_not_close_the_page", resourceCulture);
            }
        }
        
        internal static string refresh_this_page {
            get {
                return ResourceManager.GetString("refresh_this_page", resourceCulture);
            }
        }
        
        internal static string spinner_alt_text {
            get {
                return ResourceManager.GetString("spinner_alt_text", resourceCulture);
            }
        }
        
        internal static string this_may_take_a_few_minutes_we_ll_refresh {
            get {
                return ResourceManager.GetString("this_may_take_a_few_minutes_we_ll_refresh", resourceCulture);
            }
        }
        
        internal static string to_see_if_the_file_has_finished_uploading {
            get {
                return ResourceManager.GetString("to_see_if_the_file_has_finished_uploading", resourceCulture);
            }
        }
        
        internal static string uploading_file {
            get {
                return ResourceManager.GetString("uploading_file", resourceCulture);
            }
        }
        
        internal static string uploading_organisation_details {
            get {
                return ResourceManager.GetString("uploading_organisation_details", resourceCulture);
            }
        }
        
        internal static string upload_file {
            get {
                return ResourceManager.GetString("upload_file", resourceCulture);
            }
        }
        
        internal static string register_company_size {
            get {
                return ResourceManager.GetString("register_company_size", resourceCulture);
            }
        }
    }
}
